TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += B2900.db
DB += B2900.proto

#=======================================
include $(TOP)/configure/RULES
